import { Project, Floor } from '../../types/project';

export const demoProject: Project = {
  id: 'proj-demo-001',
  name: 'Demo Multi-Level Project',
  location: 'Makati City',
  buildingType: 'office',
  status: 'active',
  outputClassification: 'preliminary',
  designConditions: {
    outdoorDB: 33,
    outdoorWB: 25,
    indoorDB: 24,
    indoorRH: 50,
    altitude: 15,
    latitude: 14.55,
    longitude: 121.03,
  },
  safetyFactor: 1.1,
  diversityFactor: 0.85,
  notes: 'Demo project for UI and system testing.',
  createdAt: '2026-03-10T08:00:00Z',
  updatedAt: '2026-03-10T08:00:00Z',
};

export const demoFloors: Floor[] = [
  {
    id: 'demo-floor-1',
    projectId: 'proj-demo-001',
    floorNumber: 1,
    name: 'Reception',
    floorPlanImage: null,
    scale: 50,
    ceilingHeight: 3.2,
    rooms: [
      {
        id: 'demo-room-1',
        floorId: 'demo-floor-1',
        name: 'Reception Area',
        polygon: [{ x: 0, y: 0 }, { x: 8, y: 0 }, { x: 8, y: 6 }, { x: 0, y: 6 }],
        area: 48,
        perimeter: 28,
        spaceType: 'lobby',
        occupantCount: 8,
        lightingDensity: 12,
        equipmentLoad: 1500,
        wallConstruction: 'concrete_200mm',
        windowArea: 6,
        windowOrientation: 'N',
        windowType: 'single_clear_6mm',
        ceilingHeight: 3.2,
        notes: 'Reception and waiting area.',
      },
    ],
  },
  {
    id: 'demo-floor-2',
    projectId: 'proj-demo-001',
    floorNumber: 2,
    name: 'Workspace',
    floorPlanImage: null,
    scale: 50,
    ceilingHeight: 3.0,
    rooms: [
      {
        id: 'demo-room-2',
        floorId: 'demo-floor-2',
        name: 'Open Workspace',
        polygon: [{ x: 0, y: 0 }, { x: 12, y: 0 }, { x: 12, y: 10 }, { x: 0, y: 10 }],
        area: 120,
        perimeter: 44,
        spaceType: 'office',
        occupantCount: 30,
        lightingDensity: 15,
        equipmentLoad: 3500,
        wallConstruction: 'drywall_metal_stud',
        windowArea: 10,
        windowOrientation: 'E',
        windowType: 'single_tinted_6mm',
        ceilingHeight: 3.0,
        notes: 'Main workspace for staff.',
      },
    ],
  },
  {
    id: 'demo-floor-3',
    projectId: 'proj-demo-001',
    floorNumber: 3,
    name: 'Meeting Rooms',
    floorPlanImage: null,
    scale: 50,
    ceilingHeight: 3.0,
    rooms: [
      {
        id: 'demo-room-3',
        floorId: 'demo-floor-3',
        name: 'Conference Room',
        polygon: [{ x: 0, y: 0 }, { x: 6, y: 0 }, { x: 6, y: 5 }, { x: 0, y: 5 }],
        area: 30,
        perimeter: 22,
        spaceType: 'conference',
        occupantCount: 10,
        lightingDensity: 18,
        equipmentLoad: 2000,
        wallConstruction: 'curtain_wall',
        windowArea: 8,
        windowOrientation: 'W',
        windowType: 'double_clear',
        ceilingHeight: 3.0,
        notes: 'Room for meetings and presentations.',
      },
    ],
  },
];
