import { Project, Floor } from '../../types/project';

export const multiLevelProject: Project = {
  id: 'proj-ml-001',
  name: 'Multi-Level Commercial Complex',
  clientName: 'ML Client',
  location: 'Quezon City',
  city: 'Quezon City',
  buildingType: 'mixed',
  status: 'active',
  totalFloorArea: 268,
  floorsAboveGrade: 4,
  floorsBelowGrade: 0,
  outputClassification: 'preliminary',
  outdoorDB: 35,
  outdoorWB: 27,
  outdoorRH: 65,
  indoorDB: 23,
  indoorRH: 55,
  designConditions: {
    outdoorDB: 35,
    outdoorWB: 27,
    indoorDB: 23,
    indoorRH: 55,
    altitude: 20,
    latitude: 14.7,
    longitude: 121.1,
  },
  safetyFactor: 1.15,
  diversityFactor: 0.9,
  notes: 'Multi-level project for demo and system test.',
  createdAt: '2026-03-10T08:00:00Z',
  updatedAt: '2026-03-10T08:00:00Z',
};

export const multiLevelFloors: Floor[] = [
  {
    id: 'ml-floor-1',
    projectId: 'proj-ml-001',
    floorNumber: 1,
    name: 'Retail Ground',
    floorPlanImage: null,
    scale: 50,
    ceilingHeight: 3.5,
    rooms: [
      {
        id: 'ml-room-1',
        floorId: 'ml-floor-1',
        name: 'Retail Shop A',
        polygon: [{ x: 0, y: 0 }, { x: 8, y: 0 }, { x: 8, y: 6 }, { x: 0, y: 6 }],
        area: 48,
        perimeter: 28,
        spaceType: 'retail',
        occupantCount: 10,
        lightingDensity: 20,
        equipmentLoad: 3000,
        wallConstruction: 'brick_200mm',
        windowArea: 6,
        windowOrientation: 'NE',
        windowType: 'double_clear',
        ceilingHeight: 3.5,
        notes: 'Retail shop for demo.',
      },
    ],
  },
  {
    id: 'ml-floor-2',
    projectId: 'proj-ml-001',
    floorNumber: 2,
    name: 'Restaurant Level',
    floorPlanImage: null,
    scale: 50,
    ceilingHeight: 3.2,
    rooms: [
      {
        id: 'ml-room-2',
        floorId: 'ml-floor-2',
        name: 'Restaurant Dining',
        polygon: [{ x: 0, y: 0 }, { x: 10, y: 0 }, { x: 10, y: 8 }, { x: 0, y: 8 }],
        area: 80,
        perimeter: 36,
        spaceType: 'restaurant',
        occupantCount: 30,
        lightingDensity: 25,
        equipmentLoad: 5000,
        wallConstruction: 'curtain_wall',
        windowArea: 12,
        windowOrientation: 'SW',
        windowType: 'double_tinted',
        ceilingHeight: 3.2,
        notes: 'Restaurant dining area.',
      },
    ],
  },
  {
    id: 'ml-floor-3',
    projectId: 'proj-ml-001',
    floorNumber: 3,
    name: 'Office Level',
    floorPlanImage: null,
    scale: 50,
    ceilingHeight: 3.0,
    rooms: [
      {
        id: 'ml-room-3',
        floorId: 'ml-floor-3',
        name: 'Open Office',
        polygon: [{ x: 0, y: 0 }, { x: 12, y: 0 }, { x: 12, y: 10 }, { x: 0, y: 10 }],
        area: 120,
        perimeter: 44,
        spaceType: 'office',
        occupantCount: 40,
        lightingDensity: 15,
        equipmentLoad: 6000,
        wallConstruction: 'drywall_metal_stud',
        windowArea: 18,
        windowOrientation: 'E',
        windowType: 'single_tinted_6mm',
        ceilingHeight: 3.0,
        notes: 'Main workspace.',
      },
    ],
  },
  {
    id: 'ml-floor-4',
    projectId: 'proj-ml-001',
    floorNumber: 4,
    name: 'Hotel Level',
    floorPlanImage: null,
    scale: 50,
    ceilingHeight: 3.0,
    rooms: [
      {
        id: 'ml-room-4',
        floorId: 'ml-floor-4',
        name: 'Hotel Room',
        polygon: [{ x: 0, y: 0 }, { x: 5, y: 0 }, { x: 5, y: 4 }, { x: 0, y: 4 }],
        area: 20,
        perimeter: 18,
        spaceType: 'hotel_room',
        occupantCount: 2,
        lightingDensity: 10,
        equipmentLoad: 1200,
        wallConstruction: 'concrete_block_150mm',
        windowArea: 4,
        windowOrientation: 'NW',
        windowType: 'double_low_e',
        ceilingHeight: 3.0,
        notes: 'Sample hotel room.',
      },
    ],
  },
];
