// Default HVAC Material Unit Rates for the Philippines (PHP)
// Prices are approximate 2025-2026 retail values
// Comprehensive catalog covering all HVAC installation categories

export interface MaterialDefault {
  category: string;
  name: string;
  specification: string;
  unit: string;
  unitPricePHP: number;
}

export const MATERIAL_DEFAULTS: MaterialDefault[] = [
  // ==================== REFRIGERANT COPPER PIPE ====================
  { category: 'refrigerant_pipe', name: 'Copper Pipe 1/4"', specification: '1/4" OD Type L soft copper, 15m coil, ASTM B280', unit: 'meter', unitPricePHP: 145 },
  { category: 'refrigerant_pipe', name: 'Copper Pipe 3/8"', specification: '3/8" OD Type L soft copper, 15m coil, ASTM B280', unit: 'meter', unitPricePHP: 210 },
  { category: 'refrigerant_pipe', name: 'Copper Pipe 1/2"', specification: '1/2" OD Type L soft copper, 15m coil, ASTM B280', unit: 'meter', unitPricePHP: 320 },
  { category: 'refrigerant_pipe', name: 'Copper Pipe 5/8"', specification: '5/8" OD Type L soft copper, 15m coil, ASTM B280', unit: 'meter', unitPricePHP: 420 },
  { category: 'refrigerant_pipe', name: 'Copper Pipe 3/4"', specification: '3/4" OD Type L soft copper, 15m coil, ASTM B280', unit: 'meter', unitPricePHP: 550 },
  { category: 'refrigerant_pipe', name: 'Copper Pipe 7/8"', specification: '7/8" OD Type L hard copper, ASTM B280', unit: 'meter', unitPricePHP: 750 },
  { category: 'refrigerant_pipe', name: 'Copper Pipe 1-1/8"', specification: '1-1/8" OD Type L hard copper, ASTM B280', unit: 'meter', unitPricePHP: 1050 },
  { category: 'refrigerant_pipe', name: 'Copper Pipe 1-3/8"', specification: '1-3/8" OD Type L hard copper, ASTM B280', unit: 'meter', unitPricePHP: 1350 },
  { category: 'refrigerant_pipe', name: 'Copper Pipe 1-5/8"', specification: '1-5/8" OD Type L hard copper, ASTM B280', unit: 'meter', unitPricePHP: 1750 },
  { category: 'refrigerant_pipe', name: 'Copper Pipe 2-1/8"', specification: '2-1/8" OD Type L hard copper, ASTM B280', unit: 'meter', unitPricePHP: 2400 },

  // ==================== COPPER FITTINGS ====================
  { category: 'copper_fitting', name: 'Copper Elbow 1/4" 90°', specification: '1/4" copper long-radius elbow, wrought', unit: 'pc', unitPricePHP: 35 },
  { category: 'copper_fitting', name: 'Copper Elbow 3/8" 90°', specification: '3/8" copper long-radius elbow, wrought', unit: 'pc', unitPricePHP: 45 },
  { category: 'copper_fitting', name: 'Copper Elbow 1/2" 90°', specification: '1/2" copper long-radius elbow, wrought', unit: 'pc', unitPricePHP: 55 },
  { category: 'copper_fitting', name: 'Copper Elbow 5/8" 90°', specification: '5/8" copper long-radius elbow, wrought', unit: 'pc', unitPricePHP: 75 },
  { category: 'copper_fitting', name: 'Copper Elbow 3/4" 90°', specification: '3/4" copper long-radius elbow, wrought', unit: 'pc', unitPricePHP: 95 },
  { category: 'copper_fitting', name: 'Copper Tee 3/8"', specification: '3/8" copper tee, wrought', unit: 'pc', unitPricePHP: 65 },
  { category: 'copper_fitting', name: 'Copper Tee 1/2"', specification: '1/2" copper tee, wrought', unit: 'pc', unitPricePHP: 85 },
  { category: 'copper_fitting', name: 'Copper Tee 5/8"', specification: '5/8" copper tee, wrought', unit: 'pc', unitPricePHP: 110 },
  { category: 'copper_fitting', name: 'Copper Tee 3/4"', specification: '3/4" copper tee, wrought', unit: 'pc', unitPricePHP: 135 },
  { category: 'copper_fitting', name: 'Copper Reducer 3/8" x 1/4"', specification: 'Copper reducing coupling', unit: 'pc', unitPricePHP: 40 },
  { category: 'copper_fitting', name: 'Copper Reducer 1/2" x 3/8"', specification: 'Copper reducing coupling', unit: 'pc', unitPricePHP: 50 },
  { category: 'copper_fitting', name: 'Copper Reducer 5/8" x 3/8"', specification: 'Copper reducing coupling', unit: 'pc', unitPricePHP: 60 },
  { category: 'copper_fitting', name: 'Copper Reducer 3/4" x 1/2"', specification: 'Copper reducing coupling', unit: 'pc', unitPricePHP: 75 },
  { category: 'copper_fitting', name: 'Flare Nut 1/4"', specification: 'Brass flare nut SAE 45°, 1/4"', unit: 'pc', unitPricePHP: 25 },
  { category: 'copper_fitting', name: 'Flare Nut 3/8"', specification: 'Brass flare nut SAE 45°, 3/8"', unit: 'pc', unitPricePHP: 30 },
  { category: 'copper_fitting', name: 'Flare Nut 1/2"', specification: 'Brass flare nut SAE 45°, 1/2"', unit: 'pc', unitPricePHP: 40 },
  { category: 'copper_fitting', name: 'Flare Nut 5/8"', specification: 'Brass flare nut SAE 45°, 5/8"', unit: 'pc', unitPricePHP: 55 },
  { category: 'copper_fitting', name: 'Flare Nut 3/4"', specification: 'Brass flare nut SAE 45°, 3/4"', unit: 'pc', unitPricePHP: 65 },
  { category: 'copper_fitting', name: 'Flare Union 1/4"', specification: 'Brass flare union SAE 45°, 1/4"', unit: 'pc', unitPricePHP: 55 },
  { category: 'copper_fitting', name: 'Flare Union 3/8"', specification: 'Brass flare union SAE 45°, 3/8"', unit: 'pc', unitPricePHP: 65 },
  { category: 'copper_fitting', name: 'Flare Union 1/2"', specification: 'Brass flare union SAE 45°, 1/2"', unit: 'pc', unitPricePHP: 85 },
  { category: 'copper_fitting', name: 'Copper Cap 1/4"', specification: 'Copper end cap, wrought, 1/4"', unit: 'pc', unitPricePHP: 15 },
  { category: 'copper_fitting', name: 'Copper Cap 3/8"', specification: 'Copper end cap, wrought, 3/8"', unit: 'pc', unitPricePHP: 20 },

  // ==================== PIPE INSULATION ====================
  { category: 'pipe_insulation', name: 'Armaflex 1/4" x 3/8" thick', specification: 'Armaflex/K-Flex closed-cell elastomeric', unit: 'meter', unitPricePHP: 35 },
  { category: 'pipe_insulation', name: 'Armaflex 3/8" x 3/8" thick', specification: 'Armaflex/K-Flex closed-cell elastomeric', unit: 'meter', unitPricePHP: 42 },
  { category: 'pipe_insulation', name: 'Armaflex 1/2" x 1/2" thick', specification: 'Armaflex/K-Flex closed-cell elastomeric', unit: 'meter', unitPricePHP: 55 },
  { category: 'pipe_insulation', name: 'Armaflex 5/8" x 1/2" thick', specification: 'Armaflex/K-Flex closed-cell elastomeric', unit: 'meter', unitPricePHP: 65 },
  { category: 'pipe_insulation', name: 'Armaflex 3/4" x 1/2" thick', specification: 'Armaflex/K-Flex closed-cell elastomeric', unit: 'meter', unitPricePHP: 80 },
  { category: 'pipe_insulation', name: 'Armaflex 7/8" x 3/4" thick', specification: 'Armaflex/K-Flex closed-cell elastomeric', unit: 'meter', unitPricePHP: 110 },
  { category: 'pipe_insulation', name: 'Armaflex 1-1/8" x 3/4" thick', specification: 'Armaflex/K-Flex closed-cell elastomeric', unit: 'meter', unitPricePHP: 145 },
  { category: 'pipe_insulation', name: 'Armaflex 1-3/8" x 1" thick', specification: 'Armaflex/K-Flex closed-cell elastomeric', unit: 'meter', unitPricePHP: 195 },
  { category: 'pipe_insulation', name: 'Armaflex Sheet 3/8" x 4ft', specification: 'Armaflex sheet roll, self-adhesive, per linear foot', unit: 'ft', unitPricePHP: 180 },
  { category: 'pipe_insulation', name: 'Armaflex Adhesive 1L', specification: 'Armaflex 520 contact adhesive glue 1 liter', unit: 'can', unitPricePHP: 850 },
  { category: 'pipe_insulation', name: 'Insulation Tape (PVC)', specification: 'Self-adhesive PVC wrap tape 2" x 30m', unit: 'roll', unitPricePHP: 120 },

  // ==================== REFRIGERANT ====================
  { category: 'refrigerant', name: 'R32 Refrigerant', specification: 'R32 (Difluoromethane) 10kg cylinder, GWP 675', unit: 'kg', unitPricePHP: 850 },
  { category: 'refrigerant', name: 'R410A Refrigerant', specification: 'R410A blend 11.3kg cylinder, GWP 2088', unit: 'kg', unitPricePHP: 750 },
  { category: 'refrigerant', name: 'R22 Refrigerant', specification: 'R22 (HCFC-22) 13.6kg cylinder (phaseout)', unit: 'kg', unitPricePHP: 1200 },
  { category: 'refrigerant', name: 'R134a Refrigerant', specification: 'R134a (HFC) 13.6kg cylinder, chiller grade', unit: 'kg', unitPricePHP: 650 },
  { category: 'refrigerant', name: 'R407C Refrigerant', specification: 'R407C blend 11.3kg cylinder', unit: 'kg', unitPricePHP: 800 },
  { category: 'refrigerant', name: 'R290 Refrigerant', specification: 'R290 Propane (natural) 5kg cylinder', unit: 'kg', unitPricePHP: 450 },
  { category: 'refrigerant', name: 'Refrigerant Oil (POE)', specification: 'Polyol Ester oil 1L for R32/R410A systems', unit: 'liter', unitPricePHP: 1200 },

  // ==================== CHILLED WATER PIPE ====================
  { category: 'chilled_water_pipe', name: 'Black Iron Pipe 2" Sch40', specification: 'ASTM A53 Grade B, ERW, 6m length', unit: 'meter', unitPricePHP: 450 },
  { category: 'chilled_water_pipe', name: 'Black Iron Pipe 2-1/2" Sch40', specification: 'ASTM A53 Grade B, ERW, 6m length', unit: 'meter', unitPricePHP: 580 },
  { category: 'chilled_water_pipe', name: 'Black Iron Pipe 3" Sch40', specification: 'ASTM A53 Grade B, ERW, 6m length', unit: 'meter', unitPricePHP: 720 },
  { category: 'chilled_water_pipe', name: 'Black Iron Pipe 4" Sch40', specification: 'ASTM A53 Grade B, ERW, 6m length', unit: 'meter', unitPricePHP: 980 },
  { category: 'chilled_water_pipe', name: 'Black Iron Pipe 6" Sch40', specification: 'ASTM A53 Grade B, ERW, 6m length', unit: 'meter', unitPricePHP: 1650 },
  { category: 'chilled_water_pipe', name: 'Black Iron Pipe 8" Sch40', specification: 'ASTM A53 Grade B, ERW, 6m length', unit: 'meter', unitPricePHP: 2400 },
  { category: 'chilled_water_pipe', name: 'PPR Pipe 20mm (1/2")', specification: 'PPR hot/cold water pipe PN20, 4m length', unit: 'meter', unitPricePHP: 85 },
  { category: 'chilled_water_pipe', name: 'PPR Pipe 25mm (3/4")', specification: 'PPR hot/cold water pipe PN20, 4m length', unit: 'meter', unitPricePHP: 110 },
  { category: 'chilled_water_pipe', name: 'PPR Pipe 32mm (1")', specification: 'PPR hot/cold water pipe PN20, 4m length', unit: 'meter', unitPricePHP: 145 },

  // ==================== PIPE FITTINGS (CHW) ====================
  { category: 'pipe_fitting', name: 'GI Elbow 2" 90°', specification: 'Galvanized malleable iron elbow 2"', unit: 'pc', unitPricePHP: 180 },
  { category: 'pipe_fitting', name: 'GI Elbow 3" 90°', specification: 'Galvanized malleable iron elbow 3"', unit: 'pc', unitPricePHP: 320 },
  { category: 'pipe_fitting', name: 'GI Elbow 4" 90°', specification: 'Galvanized malleable iron elbow 4"', unit: 'pc', unitPricePHP: 480 },
  { category: 'pipe_fitting', name: 'GI Tee 2"', specification: 'Galvanized malleable iron tee 2"', unit: 'pc', unitPricePHP: 250 },
  { category: 'pipe_fitting', name: 'GI Tee 3"', specification: 'Galvanized malleable iron tee 3"', unit: 'pc', unitPricePHP: 420 },
  { category: 'pipe_fitting', name: 'GI Tee 4"', specification: 'Galvanized malleable iron tee 4"', unit: 'pc', unitPricePHP: 650 },
  { category: 'pipe_fitting', name: 'GI Union 2"', specification: 'Galvanized union fitting 2"', unit: 'pc', unitPricePHP: 350 },
  { category: 'pipe_fitting', name: 'GI Nipple 2" x 4"', specification: 'Galvanized pipe nipple 2" x 100mm', unit: 'pc', unitPricePHP: 60 },
  { category: 'pipe_fitting', name: 'GI Reducer 3" x 2"', specification: 'Galvanized concentric reducer', unit: 'pc', unitPricePHP: 280 },
  { category: 'pipe_fitting', name: 'Flange 2" 150#', specification: 'Slip-on flange ANSI 150# 2" with gasket & bolts', unit: 'set', unitPricePHP: 850 },
  { category: 'pipe_fitting', name: 'Flange 4" 150#', specification: 'Slip-on flange ANSI 150# 4" with gasket & bolts', unit: 'set', unitPricePHP: 1450 },

  // ==================== VALVES ====================
  { category: 'valve', name: 'Ball Valve 1/2" Brass', specification: 'Full-port brass ball valve 1/2", 600 WOG', unit: 'pc', unitPricePHP: 250 },
  { category: 'valve', name: 'Ball Valve 3/4" Brass', specification: 'Full-port brass ball valve 3/4", 600 WOG', unit: 'pc', unitPricePHP: 350 },
  { category: 'valve', name: 'Ball Valve 1" Brass', specification: 'Full-port brass ball valve 1", 600 WOG', unit: 'pc', unitPricePHP: 480 },
  { category: 'valve', name: 'Ball Valve 2" Cast Iron', specification: 'Flanged ball valve 2" PN16', unit: 'pc', unitPricePHP: 2500 },
  { category: 'valve', name: 'Gate Valve 2" Bronze', specification: 'Rising stem gate valve 2", 200 WOG', unit: 'pc', unitPricePHP: 3200 },
  { category: 'valve', name: 'Gate Valve 3" Cast Iron', specification: 'Flanged gate valve 3" PN16', unit: 'pc', unitPricePHP: 5500 },
  { category: 'valve', name: 'Gate Valve 4" Cast Iron', specification: 'Flanged gate valve 4" PN16', unit: 'pc', unitPricePHP: 8500 },
  { category: 'valve', name: 'Check Valve 2" Swing', specification: 'Swing check valve 2" flanged, PN16', unit: 'pc', unitPricePHP: 2800 },
  { category: 'valve', name: 'Check Valve 3" Swing', specification: 'Swing check valve 3" flanged, PN16', unit: 'pc', unitPricePHP: 4500 },
  { category: 'valve', name: 'Butterfly Valve 4"', specification: 'Wafer-type butterfly valve 4" PN16 with handle', unit: 'pc', unitPricePHP: 3500 },
  { category: 'valve', name: 'Butterfly Valve 6"', specification: 'Wafer-type butterfly valve 6" PN16 with gear', unit: 'pc', unitPricePHP: 5500 },
  { category: 'valve', name: 'Balancing Valve 2"', specification: 'Manual balancing valve with readout 2"', unit: 'pc', unitPricePHP: 8500 },
  { category: 'valve', name: 'Balancing Valve 3"', specification: 'Manual balancing valve with readout 3"', unit: 'pc', unitPricePHP: 12000 },
  { category: 'valve', name: 'Pressure Relief Valve 1/2"', specification: 'Adjustable pressure relief valve 0-10 bar', unit: 'pc', unitPricePHP: 1800 },
  { category: 'valve', name: 'Air Vent Valve 1/2"', specification: 'Automatic air vent valve 1/2" brass', unit: 'pc', unitPricePHP: 450 },
  { category: 'valve', name: 'Y-Strainer 2"', specification: 'Flanged Y-strainer 2" cast iron with SS screen', unit: 'pc', unitPricePHP: 2200 },
  { category: 'valve', name: 'Y-Strainer 4"', specification: 'Flanged Y-strainer 4" cast iron with SS screen', unit: 'pc', unitPricePHP: 4800 },
  { category: 'valve', name: 'Expansion Tank 50L', specification: 'Diaphragm expansion tank 50L, 6 bar', unit: 'pc', unitPricePHP: 8500 },
  { category: 'valve', name: 'Expansion Tank 100L', specification: 'Diaphragm expansion tank 100L, 6 bar', unit: 'pc', unitPricePHP: 15000 },

  // ==================== GI SHEET FOR DUCTWORK ====================
  { category: 'gi_sheet', name: 'G.I. Sheet Gauge 26', specification: 'Plain galvanized iron sheet 4x8 ft, 0.45mm', unit: 'sheet', unitPricePHP: 680 },
  { category: 'gi_sheet', name: 'G.I. Sheet Gauge 24', specification: 'Plain galvanized iron sheet 4x8 ft, 0.55mm', unit: 'sheet', unitPricePHP: 850 },
  { category: 'gi_sheet', name: 'G.I. Sheet Gauge 22', specification: 'Plain galvanized iron sheet 4x8 ft, 0.70mm', unit: 'sheet', unitPricePHP: 1100 },
  { category: 'gi_sheet', name: 'G.I. Sheet Gauge 20', specification: 'Plain galvanized iron sheet 4x8 ft, 0.90mm', unit: 'sheet', unitPricePHP: 1450 },
  { category: 'gi_sheet', name: 'G.I. Sheet Gauge 18', specification: 'Plain galvanized iron sheet 4x8 ft, 1.20mm', unit: 'sheet', unitPricePHP: 1950 },

  // ==================== DUCT INSULATION ====================
  { category: 'duct_insulation', name: 'PE Foam Insulation 25mm', specification: 'Closed-cell polyethylene foam 25mm with foil', unit: 'sqm', unitPricePHP: 280 },
  { category: 'duct_insulation', name: 'PE Foam Insulation 50mm', specification: 'Closed-cell polyethylene foam 50mm with foil', unit: 'sqm', unitPricePHP: 450 },
  { category: 'duct_insulation', name: 'Fiberglass Board 25mm', specification: 'Fiberglass duct board 25mm with foil facing', unit: 'sqm', unitPricePHP: 350 },
  { category: 'duct_insulation', name: 'Fiberglass Board 50mm', specification: 'Fiberglass duct board 50mm with foil facing', unit: 'sqm', unitPricePHP: 520 },
  { category: 'duct_insulation', name: 'Rubber Sheet Insulation 25mm', specification: 'Closed-cell rubber sheet 25mm, self-adhesive', unit: 'sqm', unitPricePHP: 650 },
  { category: 'duct_insulation', name: 'Fiberglass Blanket 50mm', specification: 'Fiberglass wrap blanket 50mm with foil vapor barrier', unit: 'sqm', unitPricePHP: 380 },
  { category: 'duct_insulation', name: 'Pipe Insulation Jacket (AL)', specification: 'Aluminum cladding jacket for pipe insulation per meter', unit: 'meter', unitPricePHP: 250 },

  // ==================== DUCT ACCESSORIES ====================
  { category: 'duct_accessory', name: 'Volume Damper (VCD) 8"', specification: 'GI VCD opposed blade, manual, 8"', unit: 'pc', unitPricePHP: 850 },
  { category: 'duct_accessory', name: 'Volume Damper (VCD) 10"', specification: 'GI VCD opposed blade, manual, 10"', unit: 'pc', unitPricePHP: 1050 },
  { category: 'duct_accessory', name: 'Volume Damper (VCD) 12"', specification: 'GI VCD opposed blade, manual, 12"', unit: 'pc', unitPricePHP: 1200 },
  { category: 'duct_accessory', name: 'Fire Damper (FD) 12"x12"', specification: 'UL listed fusible link fire damper 300x300mm', unit: 'pc', unitPricePHP: 7500 },
  { category: 'duct_accessory', name: 'Fire Damper (FD) 18"x12"', specification: 'UL listed fusible link fire damper 450x300mm', unit: 'pc', unitPricePHP: 9500 },
  { category: 'duct_accessory', name: 'Smoke Damper 12"x12"', specification: 'Motorized smoke damper 300x300mm with actuator', unit: 'pc', unitPricePHP: 15000 },
  { category: 'duct_accessory', name: 'Flexible Duct 4"', specification: 'Insulated flex duct 4" x 3m', unit: 'pc', unitPricePHP: 480 },
  { category: 'duct_accessory', name: 'Flexible Duct 6"', specification: 'Insulated flex duct 6" x 3m', unit: 'pc', unitPricePHP: 650 },
  { category: 'duct_accessory', name: 'Flexible Duct 8"', specification: 'Insulated flex duct 8" x 3m', unit: 'pc', unitPricePHP: 850 },
  { category: 'duct_accessory', name: 'Flexible Duct 10"', specification: 'Insulated flex duct 10" x 3m', unit: 'pc', unitPricePHP: 1100 },
  { category: 'duct_accessory', name: 'Flexible Duct 12"', specification: 'Insulated flex duct 12" x 3m', unit: 'pc', unitPricePHP: 1350 },
  { category: 'duct_accessory', name: 'Supply Diffuser 2x2 (4-way)', specification: '4-way ceiling diffuser 600x600mm, powder-coated', unit: 'pc', unitPricePHP: 1800 },
  { category: 'duct_accessory', name: 'Supply Diffuser 1x1 (4-way)', specification: '4-way ceiling diffuser 300x300mm, powder-coated', unit: 'pc', unitPricePHP: 950 },
  { category: 'duct_accessory', name: 'Return Air Grille 2x2', specification: 'Eggcrate return air grille 600x600mm, aluminum', unit: 'pc', unitPricePHP: 950 },
  { category: 'duct_accessory', name: 'Return Air Grille 12"x12"', specification: 'Eggcrate return air grille 300x300mm, aluminum', unit: 'pc', unitPricePHP: 550 },
  { category: 'duct_accessory', name: 'Linear Slot Diffuser (2-slot)', specification: '2-slot linear diffuser per foot, aluminum', unit: 'ft', unitPricePHP: 1500 },
  { category: 'duct_accessory', name: 'Linear Slot Diffuser (4-slot)', specification: '4-slot linear diffuser per foot, aluminum', unit: 'ft', unitPricePHP: 2200 },
  { category: 'duct_accessory', name: 'Fresh Air Louver 12"x12"', specification: 'Aluminum weather louver 300x300mm with bird screen', unit: 'pc', unitPricePHP: 1200 },
  { category: 'duct_accessory', name: 'Fresh Air Louver 24"x24"', specification: 'Aluminum weather louver 600x600mm with bird screen', unit: 'pc', unitPricePHP: 3200 },
  { category: 'duct_accessory', name: 'Exhaust Grille 12"x12"', specification: 'Fixed-blade exhaust grille 300x300mm', unit: 'pc', unitPricePHP: 650 },
  { category: 'duct_accessory', name: 'Jet Nozzle Diffuser 6"', specification: 'Adjustable jet nozzle diffuser 6"', unit: 'pc', unitPricePHP: 3500 },
  { category: 'duct_accessory', name: 'Canvas Connection', specification: 'Flexible canvas connection for AHU/FCU duct', unit: 'set', unitPricePHP: 350 },
  { category: 'duct_accessory', name: 'Duct Transition/Reducer', specification: 'Custom GI duct reducer fabrication per unit', unit: 'pc', unitPricePHP: 450 },
  { category: 'duct_accessory', name: 'Round-to-Rect Adapter', specification: 'GI round-to-rect transition adapter', unit: 'pc', unitPricePHP: 550 },
  { category: 'duct_accessory', name: 'TDC/TDF Flange Set', specification: 'TDC/TDF flange connector set with gasket & cleats', unit: 'set', unitPricePHP: 180 },
  { category: 'duct_accessory', name: 'Turning Vanes', specification: 'Single blade turning vanes for 90° elbow, per set', unit: 'set', unitPricePHP: 350 },

  // ==================== PVC PIPE (DRAINAGE/CONDENSATE) ====================
  { category: 'pvc_pipe', name: 'PVC Pipe 3/4" x 3m', specification: '3/4" Schedule 40 PVC pipe', unit: 'pc', unitPricePHP: 95 },
  { category: 'pvc_pipe', name: 'PVC Pipe 1" x 3m', specification: '1" Schedule 40 PVC pipe', unit: 'pc', unitPricePHP: 120 },
  { category: 'pvc_pipe', name: 'PVC Pipe 1-1/2" x 3m', specification: '1-1/2" Schedule 40 PVC pipe', unit: 'pc', unitPricePHP: 165 },
  { category: 'pvc_pipe', name: 'PVC Pipe 2" x 3m', specification: '2" Schedule 40 PVC pipe for condensate main', unit: 'pc', unitPricePHP: 210 },
  { category: 'pvc_pipe', name: 'PVC Pipe 3" x 3m', specification: '3" Schedule 40 PVC pipe', unit: 'pc', unitPricePHP: 320 },
  { category: 'pvc_pipe', name: 'PVC Pipe 4" x 3m', specification: '4" Schedule 40 PVC pipe', unit: 'pc', unitPricePHP: 420 },
  { category: 'pvc_pipe', name: 'PVC Elbow 3/4" 90°', specification: '3/4" PVC 90° elbow', unit: 'pc', unitPricePHP: 12 },
  { category: 'pvc_pipe', name: 'PVC Elbow 1" 90°', specification: '1" PVC 90° elbow', unit: 'pc', unitPricePHP: 18 },
  { category: 'pvc_pipe', name: 'PVC Tee 3/4"', specification: '3/4" PVC tee', unit: 'pc', unitPricePHP: 18 },
  { category: 'pvc_pipe', name: 'PVC Tee 1"', specification: '1" PVC tee', unit: 'pc', unitPricePHP: 25 },
  { category: 'pvc_pipe', name: 'PVC Coupling 3/4"', specification: '3/4" PVC coupling', unit: 'pc', unitPricePHP: 8 },
  { category: 'pvc_pipe', name: 'PVC Coupling 1"', specification: '1" PVC coupling', unit: 'pc', unitPricePHP: 12 },
  { category: 'pvc_pipe', name: 'PVC Clean-Out 3/4"', specification: '3/4" PVC clean-out plug', unit: 'pc', unitPricePHP: 25 },
  { category: 'pvc_pipe', name: 'PVC Solvent Cement', specification: 'PVC solvent cement 200ml can', unit: 'can', unitPricePHP: 120 },
  { category: 'pvc_pipe', name: 'Condensate Pump (Mini)', specification: 'Mini condensate removal pump 230V', unit: 'pc', unitPricePHP: 4500 },
  { category: 'pvc_pipe', name: 'Condensate Pump (Commercial)', specification: 'Commercial condensate pump 1/3HP 230V', unit: 'pc', unitPricePHP: 12000 },
  { category: 'pvc_pipe', name: 'Drain Pan (GI)', specification: 'Galvanized steel drain pan custom size per sqft', unit: 'sqft', unitPricePHP: 150 },

  // ==================== ELECTRICAL WIRE ====================
  { category: 'electrical_wire', name: 'THHN Wire 2.0mm²', specification: 'THHN stranded copper 2.0mm² (14AWG)', unit: 'meter', unitPricePHP: 22 },
  { category: 'electrical_wire', name: 'THHN Wire 3.5mm²', specification: 'THHN stranded copper 3.5mm² (12AWG)', unit: 'meter', unitPricePHP: 32 },
  { category: 'electrical_wire', name: 'THHN Wire 5.5mm²', specification: 'THHN stranded copper 5.5mm² (10AWG)', unit: 'meter', unitPricePHP: 48 },
  { category: 'electrical_wire', name: 'THHN Wire 8.0mm²', specification: 'THHN stranded copper 8.0mm² (8AWG)', unit: 'meter', unitPricePHP: 72 },
  { category: 'electrical_wire', name: 'THHN Wire 14.0mm²', specification: 'THHN stranded copper 14.0mm² (6AWG)', unit: 'meter', unitPricePHP: 125 },
  { category: 'electrical_wire', name: 'THHN Wire 22.0mm²', specification: 'THHN stranded copper 22.0mm² (4AWG)', unit: 'meter', unitPricePHP: 195 },
  { category: 'electrical_wire', name: 'THHN Wire 30.0mm²', specification: 'THHN stranded copper 30.0mm² (2AWG)', unit: 'meter', unitPricePHP: 280 },
  { category: 'electrical_wire', name: 'THHN Wire 38.0mm²', specification: 'THHN stranded copper 38.0mm² (1AWG)', unit: 'meter', unitPricePHP: 350 },
  { category: 'electrical_wire', name: 'THHN Wire 50.0mm²', specification: 'THHN stranded copper 50.0mm² (1/0AWG)', unit: 'meter', unitPricePHP: 450 },
  { category: 'electrical_wire', name: 'THHN Wire 60.0mm²', specification: 'THHN stranded copper 60.0mm² (2/0AWG)', unit: 'meter', unitPricePHP: 550 },
  { category: 'electrical_wire', name: 'Ground Wire 3.5mm² (Green)', specification: 'THHN grounding wire 3.5mm² green', unit: 'meter', unitPricePHP: 32 },
  { category: 'electrical_wire', name: 'Ground Wire 8.0mm² (Green)', specification: 'THHN grounding wire 8.0mm² green', unit: 'meter', unitPricePHP: 72 },
  { category: 'electrical_wire', name: 'Communication Wire (2C)', specification: '2-core signal/control wire 0.75mm²', unit: 'meter', unitPricePHP: 18 },
  { category: 'electrical_wire', name: 'Communication Wire (4C)', specification: '4-core signal/control wire 0.75mm²', unit: 'meter', unitPricePHP: 28 },

  // ==================== CIRCUIT BREAKERS ====================
  { category: 'electrical_breaker', name: 'MCB 15A 1P', specification: 'Miniature circuit breaker 15A single pole 240V', unit: 'pc', unitPricePHP: 350 },
  { category: 'electrical_breaker', name: 'MCB 20A 1P', specification: 'Miniature circuit breaker 20A single pole 240V', unit: 'pc', unitPricePHP: 380 },
  { category: 'electrical_breaker', name: 'MCB 20A 2P', specification: 'Miniature circuit breaker 20A 2-pole 240V', unit: 'pc', unitPricePHP: 650 },
  { category: 'electrical_breaker', name: 'MCB 30A 2P', specification: 'Miniature circuit breaker 30A 2-pole 240V', unit: 'pc', unitPricePHP: 750 },
  { category: 'electrical_breaker', name: 'MCB 40A 2P', specification: 'Miniature circuit breaker 40A 2-pole 240V', unit: 'pc', unitPricePHP: 850 },
  { category: 'electrical_breaker', name: 'MCCB 50A 3P', specification: 'Molded case circuit breaker 50A 3-pole 415V', unit: 'pc', unitPricePHP: 3500 },
  { category: 'electrical_breaker', name: 'MCCB 60A 3P', specification: 'Molded case circuit breaker 60A 3-pole 415V', unit: 'pc', unitPricePHP: 4200 },
  { category: 'electrical_breaker', name: 'MCCB 100A 3P', specification: 'Molded case circuit breaker 100A 3-pole 415V', unit: 'pc', unitPricePHP: 5500 },
  { category: 'electrical_breaker', name: 'MCCB 150A 3P', specification: 'Molded case circuit breaker 150A 3-pole 415V', unit: 'pc', unitPricePHP: 8500 },
  { category: 'electrical_breaker', name: 'MCCB 200A 3P', specification: 'Molded case circuit breaker 200A 3-pole 415V', unit: 'pc', unitPricePHP: 12000 },
  { category: 'electrical_breaker', name: 'MCCB 400A 3P', specification: 'Molded case circuit breaker 400A 3-pole 415V', unit: 'pc', unitPricePHP: 25000 },

  // ==================== ELECTRICAL ACCESSORIES ====================
  { category: 'electrical_accessory', name: 'Isolator Switch 20A', specification: 'Weather-proof isolator switch 20A 1P', unit: 'pc', unitPricePHP: 650 },
  { category: 'electrical_accessory', name: 'Isolator Switch 32A', specification: 'Weather-proof isolator switch 32A 2P', unit: 'pc', unitPricePHP: 950 },
  { category: 'electrical_accessory', name: 'Isolator Switch 60A', specification: 'Weather-proof isolator switch 60A 3P', unit: 'pc', unitPricePHP: 2200 },
  { category: 'electrical_accessory', name: 'Disconnect Switch 63A', specification: 'Fused disconnect 63A 3P', unit: 'pc', unitPricePHP: 2800 },
  { category: 'electrical_accessory', name: 'Disconnect Switch 100A', specification: 'Fused disconnect 100A 3P', unit: 'pc', unitPricePHP: 4500 },
  { category: 'electrical_accessory', name: 'PVC Conduit 1/2"', specification: 'Rigid PVC conduit 1/2" x 3m', unit: 'pc', unitPricePHP: 55 },
  { category: 'electrical_accessory', name: 'PVC Conduit 3/4"', specification: 'Rigid PVC conduit 3/4" x 3m', unit: 'pc', unitPricePHP: 85 },
  { category: 'electrical_accessory', name: 'PVC Conduit 1"', specification: 'Rigid PVC conduit 1" x 3m', unit: 'pc', unitPricePHP: 110 },
  { category: 'electrical_accessory', name: 'PVC Conduit 1-1/4"', specification: 'Rigid PVC conduit 1-1/4" x 3m', unit: 'pc', unitPricePHP: 150 },
  { category: 'electrical_accessory', name: 'PVC Conduit 2"', specification: 'Rigid PVC conduit 2" x 3m', unit: 'pc', unitPricePHP: 220 },
  { category: 'electrical_accessory', name: 'EMT Conduit 1/2"', specification: 'Electrical metallic tubing 1/2" x 3m', unit: 'pc', unitPricePHP: 180 },
  { category: 'electrical_accessory', name: 'EMT Conduit 3/4"', specification: 'Electrical metallic tubing 3/4" x 3m', unit: 'pc', unitPricePHP: 250 },
  { category: 'electrical_accessory', name: 'EMT Conduit 1"', specification: 'Electrical metallic tubing 1" x 3m', unit: 'pc', unitPricePHP: 320 },
  { category: 'electrical_accessory', name: 'Flex Metal Conduit 1/2"', specification: 'Liquid-tight flex conduit 1/2" per meter', unit: 'meter', unitPricePHP: 85 },
  { category: 'electrical_accessory', name: 'Flex Metal Conduit 3/4"', specification: 'Liquid-tight flex conduit 3/4" per meter', unit: 'meter', unitPricePHP: 120 },
  { category: 'electrical_accessory', name: 'Junction Box 4"x4"', specification: 'PVC junction box 4x4" with cover', unit: 'pc', unitPricePHP: 45 },
  { category: 'electrical_accessory', name: 'Junction Box 6"x6"', specification: 'GI junction box 6x6" with cover', unit: 'pc', unitPricePHP: 120 },
  { category: 'electrical_accessory', name: 'Pull Box 8"x8"x4"', specification: 'GI pull box 200x200x100mm', unit: 'pc', unitPricePHP: 250 },
  { category: 'electrical_accessory', name: 'Cable Tray 12" x 3m', specification: 'Perforated cable tray 300mm width x 3m', unit: 'pc', unitPricePHP: 1200 },
  { category: 'electrical_accessory', name: 'Cable Tray 18" x 3m', specification: 'Perforated cable tray 450mm width x 3m', unit: 'pc', unitPricePHP: 1800 },
  { category: 'electrical_accessory', name: 'Contactor 20A', specification: 'AC magnetic contactor 20A 3-pole 220V coil', unit: 'pc', unitPricePHP: 1200 },
  { category: 'electrical_accessory', name: 'Contactor 40A', specification: 'AC magnetic contactor 40A 3-pole 220V coil', unit: 'pc', unitPricePHP: 2500 },
  { category: 'electrical_accessory', name: 'Overload Relay 10-16A', specification: 'Thermal overload relay 10-16A', unit: 'pc', unitPricePHP: 1800 },
  { category: 'electrical_accessory', name: 'Panel Board 4-way', specification: 'Plug-in load center 4-branch 240V', unit: 'pc', unitPricePHP: 2800 },
  { category: 'electrical_accessory', name: 'Panel Board 8-way', specification: 'Plug-in load center 8-branch 240V', unit: 'pc', unitPricePHP: 4500 },
  { category: 'electrical_accessory', name: 'Panel Board 3P 12-way', specification: '3-phase panel board 12-branch 415V', unit: 'pc', unitPricePHP: 12000 },
  { category: 'electrical_accessory', name: 'Motor Starter DOL', specification: 'Direct-on-line starter enclosure up to 7.5kW', unit: 'set', unitPricePHP: 8500 },

  // ==================== HANGERS & SUPPORTS ====================
  { category: 'hanger_support', name: 'Threaded Rod 3/8" x 3m', specification: 'Galvanized threaded rod 3/8"', unit: 'pc', unitPricePHP: 85 },
  { category: 'hanger_support', name: 'Threaded Rod 1/2" x 3m', specification: 'Galvanized threaded rod 1/2"', unit: 'pc', unitPricePHP: 120 },
  { category: 'hanger_support', name: 'Threaded Rod 5/8" x 3m', specification: 'Galvanized threaded rod 5/8"', unit: 'pc', unitPricePHP: 180 },
  { category: 'hanger_support', name: 'Unistrut 41x41 x 3m', specification: 'Galvanized strut channel P1000', unit: 'meter', unitPricePHP: 280 },
  { category: 'hanger_support', name: 'Unistrut 41x62 x 3m', specification: 'Galvanized deep strut channel P1001', unit: 'meter', unitPricePHP: 380 },
  { category: 'hanger_support', name: 'Pipe Clamp 1/2"', specification: 'Galvanized pipe clamp with rubber lining', unit: 'pc', unitPricePHP: 25 },
  { category: 'hanger_support', name: 'Pipe Clamp 3/4"', specification: 'Galvanized pipe clamp with rubber lining', unit: 'pc', unitPricePHP: 30 },
  { category: 'hanger_support', name: 'Pipe Clamp 1"', specification: 'Galvanized pipe clamp with rubber lining', unit: 'pc', unitPricePHP: 35 },
  { category: 'hanger_support', name: 'Clevis Hanger 2"', specification: 'Galvanized clevis hanger 2"', unit: 'pc', unitPricePHP: 85 },
  { category: 'hanger_support', name: 'Clevis Hanger 4"', specification: 'Galvanized clevis hanger 4"', unit: 'pc', unitPricePHP: 150 },
  { category: 'hanger_support', name: 'Anchor Bolt 3/8" x 3"', specification: 'Hilti-type expansion anchor 3/8" x 3"', unit: 'pc', unitPricePHP: 18 },
  { category: 'hanger_support', name: 'Anchor Bolt 1/2" x 4"', specification: 'Hilti-type expansion anchor 1/2" x 4"', unit: 'pc', unitPricePHP: 28 },
  { category: 'hanger_support', name: 'Beam Clamp 3/8"', specification: 'Galvanized steel beam clamp 3/8"', unit: 'pc', unitPricePHP: 45 },
  { category: 'hanger_support', name: 'Spring Hanger (1-5 TR)', specification: 'Spring isolation hanger for small units', unit: 'pc', unitPricePHP: 350 },
  { category: 'hanger_support', name: 'Vibration Pad (Neoprene)', specification: 'Neoprene anti-vibration pad 4"x4"x1"', unit: 'pc', unitPricePHP: 180 },
  { category: 'hanger_support', name: 'Vibration Isolator Spring', specification: 'Spring-type anti-vibration mount 500kg', unit: 'pc', unitPricePHP: 850 },
  { category: 'hanger_support', name: 'Equipment Base Frame', specification: 'Steel base frame for outdoor unit (pair)', unit: 'pair', unitPricePHP: 1200 },
  { category: 'hanger_support', name: 'Duct Trapeze Set', specification: 'Angle bar trapeze hanger with rod, nuts, washers', unit: 'set', unitPricePHP: 250 },
  { category: 'hanger_support', name: 'C-Channel 50x25mm x 3m', specification: 'Light-gauge C-channel galvanized, 3m', unit: 'pc', unitPricePHP: 180 },
  { category: 'hanger_support', name: 'Angle Bar 40x40x3mm x 3m', specification: 'Galvanized angle bar, 3m length', unit: 'pc', unitPricePHP: 250 },

  // ==================== BRAZING & WELDING ====================
  { category: 'brazing', name: 'Silver Brazing Rod (15%)', specification: '15% silver brazing alloy 1.6mm x 500mm', unit: 'pc', unitPricePHP: 85 },
  { category: 'brazing', name: 'Silver Brazing Rod (45%)', specification: '45% silver brazing alloy 1.6mm x 500mm', unit: 'pc', unitPricePHP: 250 },
  { category: 'brazing', name: 'Copper-Phosphorus Rod', specification: 'BCuP rod 2.4mm (no flux for Cu-Cu)', unit: 'pc', unitPricePHP: 35 },
  { category: 'brazing', name: 'Nitrogen Gas (OFN)', specification: 'Oxygen-free nitrogen tank refill 40L', unit: 'tank', unitPricePHP: 1200 },
  { category: 'brazing', name: 'Acetylene Gas', specification: 'Dissolved acetylene cylinder refill', unit: 'tank', unitPricePHP: 2500 },
  { category: 'brazing', name: 'Oxygen Gas', specification: 'Medical/welding oxygen cylinder refill 40L', unit: 'tank', unitPricePHP: 800 },
  { category: 'brazing', name: 'Brazing Flux Paste', specification: 'Silver brazing flux paste 250g jar', unit: 'jar', unitPricePHP: 450 },
  { category: 'brazing', name: 'Welding Rod 6011 3.2mm', specification: 'E6011 welding electrode 3.2mm, 5kg box', unit: 'box', unitPricePHP: 650 },
  { category: 'brazing', name: 'Welding Rod 7018 3.2mm', specification: 'E7018 low-hydrogen electrode 3.2mm, 5kg', unit: 'box', unitPricePHP: 950 },

  // ==================== CONTROLS & AUTOMATION ====================
  { category: 'controls', name: 'Wired Remote Controller', specification: 'Wall-mount wired thermostat/controller', unit: 'pc', unitPricePHP: 3500 },
  { category: 'controls', name: 'Wireless Remote', specification: 'IR wireless remote (OEM replacement)', unit: 'pc', unitPricePHP: 1200 },
  { category: 'controls', name: 'Programmable Thermostat', specification: '7-day programmable digital thermostat 24V', unit: 'pc', unitPricePHP: 5500 },
  { category: 'controls', name: 'Smart Wi-Fi Thermostat', specification: 'Wi-Fi smart thermostat with app control', unit: 'pc', unitPricePHP: 12000 },
  { category: 'controls', name: 'Group Controller (8-unit)', specification: 'Centralized group controller up to 8 units', unit: 'set', unitPricePHP: 25000 },
  { category: 'controls', name: 'Central Controller (64-unit)', specification: 'BMS-grade controller up to 64 units', unit: 'set', unitPricePHP: 85000 },
  { category: 'controls', name: 'Room Temp Sensor', specification: 'Wall-mount room temp sensor NTC/Pt1000', unit: 'pc', unitPricePHP: 1500 },
  { category: 'controls', name: 'Duct Temp Sensor', specification: 'Insertion-type duct temperature sensor', unit: 'pc', unitPricePHP: 2200 },
  { category: 'controls', name: 'Humidity Sensor (Room)', specification: 'Wall-mount room humidity/temp sensor', unit: 'pc', unitPricePHP: 3500 },
  { category: 'controls', name: 'CO2 Sensor (Duct)', specification: 'Duct-mount CO2 sensor 0-2000ppm', unit: 'pc', unitPricePHP: 15000 },
  { category: 'controls', name: 'Diff. Pressure Switch', specification: 'Air differential pressure switch (filter alarm)', unit: 'pc', unitPricePHP: 2800 },
  { category: 'controls', name: 'Flow Switch 1"', specification: 'Paddle-type water flow switch 1"', unit: 'pc', unitPricePHP: 3500 },
  { category: 'controls', name: 'Motorized Valve 2-Way 1"', specification: 'Motorized 2-way modulating valve with actuator', unit: 'set', unitPricePHP: 12000 },
  { category: 'controls', name: 'Motorized Valve 3-Way 1"', specification: 'Motorized 3-way mixing valve with actuator', unit: 'set', unitPricePHP: 15000 },
  { category: 'controls', name: 'VFD 1HP', specification: 'Variable frequency drive 0.75kW 1-phase', unit: 'pc', unitPricePHP: 8500 },
  { category: 'controls', name: 'VFD 3HP', specification: 'Variable frequency drive 2.2kW 3-phase', unit: 'pc', unitPricePHP: 15000 },
  { category: 'controls', name: 'VFD 5HP', specification: 'Variable frequency drive 3.7kW 3-phase', unit: 'pc', unitPricePHP: 22000 },
  { category: 'controls', name: 'VFD 10HP', specification: 'Variable frequency drive 7.5kW 3-phase', unit: 'pc', unitPricePHP: 35000 },
  { category: 'controls', name: 'BMS DDC Controller', specification: 'Direct Digital Control panel with I/O modules', unit: 'set', unitPricePHP: 45000 },
  { category: 'controls', name: 'Damper Actuator (On/Off)', specification: 'Spring-return damper actuator 24V on/off', unit: 'pc', unitPricePHP: 4500 },
  { category: 'controls', name: 'Damper Actuator (Modulating)', specification: 'Spring-return actuator 24V modulating 0-10V', unit: 'pc', unitPricePHP: 8500 },

  // ==================== FANS & VENTILATION ====================
  { category: 'fan', name: 'Exhaust Fan 8" (Wall)', specification: 'Wall-mount exhaust fan 8" 220V', unit: 'pc', unitPricePHP: 1500 },
  { category: 'fan', name: 'Exhaust Fan 10" (Wall)', specification: 'Wall-mount exhaust fan 10" 220V', unit: 'pc', unitPricePHP: 2200 },
  { category: 'fan', name: 'Exhaust Fan 12" (Wall)', specification: 'Wall-mount exhaust fan 12" 220V', unit: 'pc', unitPricePHP: 3500 },
  { category: 'fan', name: 'Exhaust Fan 16" (Industrial)', specification: 'Industrial exhaust fan 16" 220V', unit: 'pc', unitPricePHP: 5500 },
  { category: 'fan', name: 'Ceiling Exhaust 6" Duct', specification: 'Ceiling-mount exhaust fan 6" duct type', unit: 'pc', unitPricePHP: 2800 },
  { category: 'fan', name: 'Ceiling Exhaust 8" Duct', specification: 'Ceiling-mount exhaust fan 8" duct type', unit: 'pc', unitPricePHP: 4200 },
  { category: 'fan', name: 'Inline Duct Fan 6"', specification: 'Mixed-flow inline duct fan 6" 150mm', unit: 'pc', unitPricePHP: 5500 },
  { category: 'fan', name: 'Inline Duct Fan 8"', specification: 'Mixed-flow inline duct fan 8" 200mm', unit: 'pc', unitPricePHP: 8500 },
  { category: 'fan', name: 'Inline Duct Fan 10"', specification: 'Mixed-flow inline duct fan 10" 250mm', unit: 'pc', unitPricePHP: 12000 },
  { category: 'fan', name: 'Centrifugal Blower 1HP', specification: 'Forward-curved centrifugal blower 1HP 3-phase', unit: 'pc', unitPricePHP: 25000 },
  { category: 'fan', name: 'Centrifugal Blower 2HP', specification: 'Forward-curved centrifugal blower 2HP 3-phase', unit: 'pc', unitPricePHP: 35000 },
  { category: 'fan', name: 'Centrifugal Blower 5HP', specification: 'Forward-curved centrifugal blower 5HP 3-phase', unit: 'pc', unitPricePHP: 55000 },
  { category: 'fan', name: 'Fresh Air Fan 1/2HP', specification: 'Fresh air supply fan with filter box 1/2HP', unit: 'set', unitPricePHP: 18000 },
  { category: 'fan', name: 'Kitchen Hood Exhaust Fan', specification: 'Belt-driven upblast exhaust fan', unit: 'pc', unitPricePHP: 35000 },

  // ==================== FILTERS ====================
  { category: 'filter', name: 'Pre-Filter Panel 2"', specification: 'Washable panel pre-filter MERV 4, 2"', unit: 'pc', unitPricePHP: 350 },
  { category: 'filter', name: 'Pre-Filter Panel 4"', specification: 'Washable panel pre-filter MERV 6, 4"', unit: 'pc', unitPricePHP: 550 },
  { category: 'filter', name: 'Bag Filter 2-pocket', specification: '2-pocket bag filter MERV 11, 24x24"', unit: 'pc', unitPricePHP: 1200 },
  { category: 'filter', name: 'Bag Filter 6-pocket', specification: '6-pocket bag filter MERV 13, 24x24"', unit: 'pc', unitPricePHP: 2500 },
  { category: 'filter', name: 'HEPA Filter 24x24x12"', specification: 'HEPA 99.97% @ 0.3μm, 24x24x12"', unit: 'pc', unitPricePHP: 8500 },
  { category: 'filter', name: 'Carbon Filter 24x24x2"', specification: 'Activated carbon panel filter 24x24x2"', unit: 'pc', unitPricePHP: 3500 },
  { category: 'filter', name: 'V-Bank Filter MERV 14', specification: 'V-bank compact filter MERV 14, 24x24x12"', unit: 'pc', unitPricePHP: 4500 },
  { category: 'filter', name: 'Filter Housing/Frame', specification: 'GI filter holding frame for 24x24" filter', unit: 'pc', unitPricePHP: 850 },

  // ==================== CHILLED WATER ACCESSORIES ====================
  { category: 'chw_accessory', name: 'Pressure Gauge 0-10 bar', specification: 'Bourdon tube pressure gauge 4" dial', unit: 'pc', unitPricePHP: 850 },
  { category: 'chw_accessory', name: 'Temperature Gauge', specification: 'Bi-metal thermometer 5" dial, 0-120°C', unit: 'pc', unitPricePHP: 650 },
  { category: 'chw_accessory', name: 'Sight Glass 1"', specification: 'Inline sight glass with moisture indicator', unit: 'pc', unitPricePHP: 1800 },
  { category: 'chw_accessory', name: 'Flow Meter 2"', specification: 'Electromagnetic flow meter 2" flanged', unit: 'pc', unitPricePHP: 45000 },
  { category: 'chw_accessory', name: 'Water Treatment Chemical', specification: 'Closed-loop corrosion inhibitor 25L', unit: 'pail', unitPricePHP: 8500 },
  { category: 'chw_accessory', name: 'Pipe Primer Paint', specification: 'Red oxide primer for piping per liter', unit: 'liter', unitPricePHP: 350 },
  { category: 'chw_accessory', name: 'Pipe Finish Paint', specification: 'Epoxy finish coat for piping per liter', unit: 'liter', unitPricePHP: 550 },
  { category: 'chw_accessory', name: 'Pipe ID Labels', specification: 'Self-adhesive pipe identification labels', unit: 'set', unitPricePHP: 120 },
  { category: 'chw_accessory', name: 'Flex Connector 2"', specification: 'Rubber flexible connector 2" flanged', unit: 'pc', unitPricePHP: 2800 },
  { category: 'chw_accessory', name: 'Flex Connector 4"', specification: 'Rubber flexible connector 4" flanged', unit: 'pc', unitPricePHP: 4500 },

  // ==================== MISCELLANEOUS ====================
  { category: 'misc', name: 'Manifold Gauge Set', specification: 'Manifold gauge hose set 3-way R410A/R32', unit: 'set', unitPricePHP: 2500 },
  { category: 'misc', name: 'Aluminum Foil Tape', specification: 'Aluminum foil tape 2" x 50m', unit: 'roll', unitPricePHP: 280 },
  { category: 'misc', name: 'Duct Sealant/Mastic', specification: 'Duct sealant/mastic 1 gallon', unit: 'gal', unitPricePHP: 650 },
  { category: 'misc', name: 'Silicone Sealant', specification: 'Neutral cure silicone 300ml cartridge', unit: 'pc', unitPricePHP: 280 },
  { category: 'misc', name: 'Cable Tie 300mm (100pcs)', specification: 'Nylon cable tie 300mm x 4.8mm', unit: 'pack', unitPricePHP: 85 },
  { category: 'misc', name: 'Cable Tie 200mm (100pcs)', specification: 'Nylon cable tie 200mm x 3.6mm', unit: 'pack', unitPricePHP: 55 },
  { category: 'misc', name: 'Drain Hose 16mm', specification: 'Corrugated drain hose 16mm ID', unit: 'meter', unitPricePHP: 25 },
  { category: 'misc', name: 'Drain Hose 20mm', specification: 'Corrugated drain hose 20mm ID', unit: 'meter', unitPricePHP: 35 },
  { category: 'misc', name: 'AC Putty/Clay', specification: 'AC wall sealant clay 500g', unit: 'pc', unitPricePHP: 60 },
  { category: 'misc', name: 'Wall Sleeve 3"', specification: 'PVC wall sleeve 3" pass-through 300mm', unit: 'pc', unitPricePHP: 120 },
  { category: 'misc', name: 'Wall Sleeve 4"', specification: 'PVC wall sleeve 4" pass-through 300mm', unit: 'pc', unitPricePHP: 180 },
  { category: 'misc', name: 'Outdoor Bracket (Wall)', specification: 'Heavy-duty wall bracket for ODU (pair)', unit: 'pair', unitPricePHP: 450 },
  { category: 'misc', name: 'Outdoor Bracket (Ground)', specification: 'Ground stand bracket for ODU (pair)', unit: 'pair', unitPricePHP: 650 },
  { category: 'misc', name: 'Roof Curb (Fabricated)', specification: 'GI fabricated roof curb for RTU', unit: 'pc', unitPricePHP: 8500 },
  { category: 'misc', name: 'Access Panel 12"x12"', specification: 'Hinged access panel 300x300mm ceiling', unit: 'pc', unitPricePHP: 550 },
  { category: 'misc', name: 'Access Panel 24"x24"', specification: 'Hinged access panel 600x600mm ceiling', unit: 'pc', unitPricePHP: 1200 },
  { category: 'misc', name: 'Fire Stop Sealant', specification: 'Intumescent fire stop sealant 310ml', unit: 'pc', unitPricePHP: 850 },
  { category: 'misc', name: 'Fire Collar 4"', specification: 'Intumescent fire collar for pipe 4"', unit: 'pc', unitPricePHP: 2500 },
  { category: 'misc', name: 'Fire-Rated Pipe Sleeve', specification: 'Fire-rated pipe sleeve assembly', unit: 'set', unitPricePHP: 1500 },
  { category: 'misc', name: 'Cork Sheet 6mm', specification: 'Cork insulation sheet for pipe support', unit: 'sqm', unitPricePHP: 250 },
  { category: 'misc', name: 'Teflon Tape 1/2"', specification: 'PTFE thread seal tape 1/2" x 10m', unit: 'roll', unitPricePHP: 15 },
  { category: 'misc', name: 'Pipe Thread Sealant', specification: 'Pipe dope/thread sealant 250ml', unit: 'pc', unitPricePHP: 280 },
  { category: 'misc', name: 'Touch-Up Paint', specification: 'Equipment touch-up spray paint 400ml', unit: 'can', unitPricePHP: 350 },
  { category: 'misc', name: 'Safety Signage Set', specification: 'HVAC safety warning signage set', unit: 'set', unitPricePHP: 450 },
  { category: 'misc', name: 'Equipment Nameplate', specification: 'Engraved SS equipment ID nameplate', unit: 'pc', unitPricePHP: 350 },
  { category: 'misc', name: 'As-Built Drawings', specification: 'As-built drawing reproduction per A1 sheet', unit: 'sheet', unitPricePHP: 250 },
  { category: 'misc', name: 'O&M Manual', specification: 'Operations & maintenance manual set', unit: 'set', unitPricePHP: 5000 },
  { category: 'misc', name: 'Commissioning Report', specification: 'System commissioning and testing report', unit: 'set', unitPricePHP: 8500 },
];
